name: Memcached Cli
version: '@version'
build: '@build'
commands:
  - in2pire.memcached.cli.command.get
  - in2pire.memcached.cli.command.get-first
  - in2pire.memcached.cli.command.get-keys
  - in2pire.memcached.cli.command.sizes
  - in2pire.memcached.cli.command.settings
  - in2pire.memcached.cli.command.slabs
  - in2pire.memcached.cli.command.stats
